[package]
name = "rust-backend-with-actix-web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
uuid ={ version = "0.8", features = ["v4"]}
serde = {version = "1", features = ["derive"] }
